---
name: Feature branch CI/CD Pipeline

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - non-existing-branch
  pull_request:
    branches:
      - master

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry==1.6.1
          poetry --version
          poetry config virtualenvs.in-project true

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install dependencies
        if: ${{ steps.setup-python.outputs.cache-hit != 'true' }}
        run: poetry install --without beam --sync

  run-unit-tests:
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry==1.6.1
          poetry --version
          poetry config virtualenvs.in-project true

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install dependencies
        if: ${{ steps.setup-python.outputs.cache-hit != 'true' }}
        run: poetry install --without beam --sync

      - name: Run pre-commit hooks
        run: make pre-commit

      - name: Run unit tests
        run: make unit-tests

      - name: Upload unit tests coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml

  push-docker-image:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry==1.6.1
          poetry --version
          poetry config virtualenvs.in-project true

  upload-pipelines:
    needs: push-docker-image
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry==1.6.1
          poetry --version
          poetry config virtualenvs.in-project true

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install dependencies
        if: ${{ steps.setup-python.outputs.cache-hit != 'true' }}
        run: poetry install --without beam --sync

      - name: Get GCP credentials
        uses: google-github-actions/auth@v2
        id: get-gcp-credentials
        with:
          credentials_json: ${{ secrets.TF_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Compile pipelines
        run: |
          make set-current-env-vars
          make compile pipeline=training
          make compile pipeline=deployment
          gsutil cp training.json ${VERTEX_PIPELINE_ROOT}
          gsutil cp deployment.json ${VERTEX_PIPELINE_ROOT}

  run-training-pipeline:
    needs: upload-pipelines
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry==1.6.1
          poetry --version
          poetry config virtualenvs.in-project true

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install dependencies
        if: ${{ steps.setup-python.outputs.cache-hit != 'true' }}
        run: poetry install --without beam --sync

      - name: Run training pipeline
        run: |
          echo ${TF_SERVICE_ACCOUNT_KEY} > key.json
          export GOOGLE_APPLICATION_CREDENTIALS=key.json
          make set-current-env-vars
          make run pipeline=training
        env:
          TF_SERVICE_ACCOUNT_KEY: ${{ secrets.TF_SERVICE_ACCOUNT_KEY }}

  run-deployment-pipeline:
    needs: run-training-pipeline
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry==1.6.1
          poetry --version
          poetry config virtualenvs.in-project true

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install dependencies
        if: ${{ steps.setup-python.outputs.cache-hit != 'true' }}
        run: poetry install --without beam --sync

      - name: Run deployment pipeline
        run: |
          echo ${TF_SERVICE_ACCOUNT_KEY} > key.json
          export GOOGLE_APPLICATION_CREDENTIALS=key.json
          make set-current-env-vars
          make run pipeline=deployment
